module.exports = {
	"JWT_SECRET": "somesupersecretsecret",
	"SUCCESS_CODE": 200,
	"ACCEPTED_CODE": 202,

	"UNAUTHORIZED_CODE": 401,
	"FORBIDDEN_CODE": 403,
	"BAD_REQUEST_CODE": 400,

	"SERVER_ERROR_CODE": 500,
	"LIMIT_PER_PAGE": 10
};
